"""
Mock liboqs for testing.

This provides a minimal mock of liboqs.KeyEncapsulation for testing when
the real liboqs-python is not installed on the system.

In production, this must be replaced with the real liboqs-python.

Security: This is for MVP testing only. Never use in production.
"""

import os


class MockKeyEncapsulation:
    """Mock ML-KEM-768 key encapsulation for testing."""

    # Removed _encap_cache as we now use deterministic derivation

    def __init__(self, variant: str = "ML-KEM-768", secret_key: bytes = None):
        """Initialize mock KEM."""
        self.variant = variant
        self.secret_key = secret_key
        
        # Deterministic but pseudo-random values for testing
        # In real liboqs, these would be generated by NIST ML-KEM
        if variant == "ML-KEM-768":
            self.public_key_size = 1184
            self.secret_key_size = 2400
            self.ciphertext_size = 1088
            self.shared_secret_size = 32
        else:
            raise ValueError(f"Unsupported variant: {variant}")

    def generate_keypair(self) -> bytes:
        """Generate mock keypair and return public key."""
        self.public_key = os.urandom(self.public_key_size)
        # CHEAT FOR MOCK: Store the public key inside the secret key so we can 
        # deterministically recover it during decapsulation in another process!
        random_padding = os.urandom(self.secret_key_size - self.public_key_size)
        self.secret_key = self.public_key + random_padding
        return self.public_key

    def export_secret_key(self) -> bytes:
        """Export the secret key."""
        if self.secret_key is None:
            raise RuntimeError("No secret key generated yet")
        return self.secret_key

    def encap_secret(self, public_key: bytes) -> tuple:
        """Encapsulate shared secret."""
        if len(public_key) != self.public_key_size:
            raise ValueError(f"Invalid public key size: {len(public_key)}")
        
        # Generate random ciphertext
        ciphertext = os.urandom(self.ciphertext_size)
        
        # Deterministically derive shared_secret from ciphertext + public_key
        import hashlib
        shared_secret = hashlib.sha256(ciphertext + public_key).digest()[:self.shared_secret_size]
        
        return ciphertext, shared_secret

    def decap_secret(self, ciphertext: bytes) -> bytes:
        """Decapsulate shared secret."""
        if len(ciphertext) != self.ciphertext_size:
            raise ValueError(f"Invalid ciphertext size: {len(ciphertext)}")
        
        if self.secret_key is None:
            raise RuntimeError("No secret key loaded")
        
        # Extract the public key that we hid inside the secret key
        public_key = self.secret_key[:self.public_key_size]
        
        # Deterministically derive the EXACT same shared_secret!
        import hashlib
        shared_secret = hashlib.sha256(ciphertext + public_key).digest()[:self.shared_secret_size]
        return shared_secret


# Mock module-level oqs.KeyEncapsulation
KeyEncapsulation = MockKeyEncapsulation

