"""
Mock liboqs for testing.

This provides a minimal mock of liboqs.KeyEncapsulation for testing when
the real liboqs-python is not installed on the system.

In production, this must be replaced with the real liboqs-python.

Security: This is for MVP testing only. Never use in production.
"""

import os


class MockKeyEncapsulation:
    """Mock ML-KEM-768 key encapsulation for testing."""

    # Class-level cache for roundtrip testing
    _encap_cache = {}

    def __init__(self, variant: str = "ML-KEM-768", secret_key: bytes = None):
        """Initialize mock KEM."""
        self.variant = variant
        self.secret_key = secret_key
        
        # Deterministic but pseudo-random values for testing
        # In real liboqs, these would be generated by NIST ML-KEM
        if variant == "ML-KEM-768":
            self.public_key_size = 1184
            self.secret_key_size = 2400
            self.ciphertext_size = 1088
            self.shared_secret_size = 32
        else:
            raise ValueError(f"Unsupported variant: {variant}")

    def generate_keypair(self) -> bytes:
        """Generate mock keypair and return public key."""
        # In real liboqs, this returns public_key bytes
        # Here we return deterministic bytes for testing
        self.public_key = os.urandom(self.public_key_size)
        self.secret_key = os.urandom(self.secret_key_size)
        return self.public_key

    def export_secret_key(self) -> bytes:
        """Export the secret key."""
        if self.secret_key is None:
            raise RuntimeError("No secret key generated yet")
        return self.secret_key

    def encap_secret(self, public_key: bytes) -> tuple:
        """Encapsulate shared secret."""
        if len(public_key) != self.public_key_size:
            raise ValueError(f"Invalid public key size: {len(public_key)}")
        
        # Generate mock ciphertext and shared secret
        # In real liboqs, these are derived from the public key
        ciphertext = os.urandom(self.ciphertext_size)
        shared_secret = os.urandom(self.shared_secret_size)
        
        # Store in cache for deterministic decap with this public key
        # Use the public key as the cache key
        cache_key = (id(public_key), public_key)
        self._encap_cache[cache_key] = (ciphertext, shared_secret)
        
        return ciphertext, shared_secret

    def decap_secret(self, ciphertext: bytes) -> bytes:
        """Decapsulate shared secret."""
        if len(ciphertext) != self.ciphertext_size:
            raise ValueError(f"Invalid ciphertext size: {len(ciphertext)}")
        
        if self.secret_key is None:
            raise RuntimeError("No secret key loaded")
        
        # For mock: look up in cache for matching ciphertext
        for (pk_id, pk_bytes), (ct, ss) in self._encap_cache.items():
            if ct == ciphertext:
                return ss
        
        # If not in cache (fresh instance), return deterministic based on CT and SK
        # This won't match in real usage, which is fine for mock testing
        import hashlib
        h = hashlib.sha256(ciphertext + self.secret_key).digest()
        return h[:self.shared_secret_size]


# Mock module-level oqs.KeyEncapsulation
KeyEncapsulation = MockKeyEncapsulation

